version: "3.8"

services:
  echo-dev: # golang web
    build: ./
    container_name: fl-server
    ports: 
      - "3000:3000"
    tty: true
    volumes:
      - .env:/go/apps/HCCTV/src/.env
      - ./src:/go/apps/HCCTV/src
  nginx: # loadbalancer
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/static/error.html:/etc/nginx/static/error.html
#    env_file: .env
  dev_db: # db for scheduling with client id
    image: mysql/mysql-server
    container_name: dev_db
    restart: always
    env_file: .env
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./dev/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d 
  logger_db: # db for server log
    image: mongo
    container_name: logger_db
    restart: always
    env_file: .env
    volumes:
      - .docker/logger-db/initdb.d/create-app-user.sh:/docker-entrypoint-initdb.d/create-app-user.sh
     

